# Generated by Django 2.0.6 on 2020-05-06 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AddressBook', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=25)),
                ('firstname', models.CharField(max_length=25)),
                ('dateAdded', models.DateTimeField(auto_now_add=True)),
                ('groupCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AddressBook.GroupCategory')),
            ],
        ),
    ]
